apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - service-account.yaml
  - api.yaml
  - api-hpa.yaml
  - worker.yaml
  - worker-hpa.yaml
  - disruption-budgets.yaml
  - topic-bootstrap-job.yaml
